# Generated by Django 3.2.7 on 2021-09-27 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='pathway',
        ),
        migrations.AddField(
            model_name='option',
            name='children',
            field=models.ManyToManyField(related_name='children_options', to='backend.Option'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='start_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.option'),
        ),
    ]
