# Generated by Django 3.2.7 on 2021-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_tutoring_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, related_name='children_options', to='backend.Option'),
        ),
    ]
