# Generated by Django 3.2.7 on 2021-09-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_option_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_option', to='backend.Option'),
        ),
    ]
