# Generated by Django 3.2.7 on 2021-09-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_option_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='children',
        ),
        migrations.AddField(
            model_name='option',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.option'),
        ),
    ]
