# Generated by Django 3.2.7 on 2021-09-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210928_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='start_option',
        ),
        migrations.AddField(
            model_name='pathway',
            name='pathway',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
