# Generated by Django 3.2.7 on 2021-09-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210928_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='category',
            field=models.ManyToManyField(related_name='pathways', to='backend.Category'),
        ),
    ]
