# Generated by Django 3.2.7 on 2021-09-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_pathway_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='pathway',
            field=models.TextField(default='{}'),
        ),
    ]
