# Generated by Django 3.2.7 on 2021-09-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('money', models.FloatField()),
                ('hours', models.IntegerField(default=40)),
                ('duration', models.IntegerField()),
                ('categories', models.ManyToManyField(null=True, to='tests.Category')),
            ],
            options={
                'ordering': ['-name'],
                'abstract': False,
            },
        ),
    ]
