# Generated by Django 3.2.7 on 2021-09-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(to='tests.Category'),
        ),
    ]
