# Generated by Django 3.2.7 on 2021-09-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_job_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('categories', models.ManyToManyField(to='tests.Category')),
            ],
        ),
        migrations.RenameModel(
            old_name='Job',
            new_name='Job1',
        ),
        migrations.CreateModel(
            name='Job2',
            fields=[
                ('option2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.option2')),
                ('money', models.FloatField()),
                ('hours', models.IntegerField(default=40)),
                ('duration', models.IntegerField()),
            ],
            bases=('tests.option2',),
        ),
    ]
