# Generated by Django 3.2.7 on 2021-09-23 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210923_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job2',
            name='option2_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.option2'),
        ),
    ]
