# Generated by Django 3.2.7 on 2021-09-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_job2_option2_ptr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job1',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='job2',
            options={'verbose_name_plural': 'Jobs - 2'},
        ),
        migrations.AlterModelOptions(
            name='option2',
            options={'verbose_name_plural': 'Options - 2'},
        ),
    ]
